import type { CSSProperties } from 'react';

export const getBuilderStyles = (colorScheme: 'light' | 'dark') => {
  const isDark = colorScheme === 'dark';

  return {
    root: {
      display: 'flex',
      flexDirection: 'column',
      gap: '12px',
      padding: '16px',
      color: isDark ? '#f9fafb' : '#111827',
      fontFamily:
        'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      height: '100%',
      boxSizing: 'border-box',
      overflow: 'auto',
    } satisfies CSSProperties,
    title: {
      fontSize: '18px',
      lineHeight: 1.3,
      margin: 0,
    } satisfies CSSProperties,
    muted: {
      color: isDark ? '#9ca3af' : '#6b7280',
      fontSize: '13px',
      lineHeight: 1.5,
      margin: 0,
    } satisfies CSSProperties,
    steps: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '6px',
    } satisfies CSSProperties,
    stepChip: {
      border: `1px solid ${isDark ? '#374151' : '#e5e7eb'}`,
      borderRadius: '999px',
      padding: '4px 10px',
      fontSize: '12px',
      background: isDark ? '#111827' : '#ffffff',
    } satisfies CSSProperties,
    stepChipActive: {
      borderColor: isDark ? '#93c5fd' : '#2563eb',
      color: isDark ? '#93c5fd' : '#1d4ed8',
      background: isDark ? '#0f172a' : '#eff6ff',
    } satisfies CSSProperties,
    box: {
      border: `1px solid ${isDark ? '#374151' : '#e5e7eb'}`,
      borderRadius: '8px',
      padding: '12px',
      background: isDark ? '#111827' : '#ffffff',
      display: 'flex',
      flexDirection: 'column',
      gap: '10px',
    } satisfies CSSProperties,
    label: {
      color: isDark ? '#9ca3af' : '#6b7280',
      fontSize: '12px',
      lineHeight: 1.4,
    } satisfies CSSProperties,
    row: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '8px',
      alignItems: 'center',
    } satisfies CSSProperties,
    input: {
      border: `1px solid ${isDark ? '#4b5563' : '#d1d5db'}`,
      borderRadius: '6px',
      padding: '8px 10px',
      background: isDark ? '#0b1220' : '#ffffff',
      color: isDark ? '#f9fafb' : '#111827',
      fontSize: '13px',
      minWidth: '120px',
      boxSizing: 'border-box',
    } satisfies CSSProperties,
    select: {
      border: `1px solid ${isDark ? '#4b5563' : '#d1d5db'}`,
      borderRadius: '6px',
      padding: '8px 10px',
      background: isDark ? '#0b1220' : '#ffffff',
      color: isDark ? '#f9fafb' : '#111827',
      fontSize: '13px',
      minWidth: '140px',
    } satisfies CSSProperties,
    table: {
      width: '100%',
      borderCollapse: 'collapse',
      fontSize: '12px',
    } satisfies CSSProperties,
    th: {
      textAlign: 'left',
      padding: '6px 4px',
      borderBottom: `1px solid ${isDark ? '#374151' : '#e5e7eb'}`,
      color: isDark ? '#9ca3af' : '#6b7280',
      fontWeight: 600,
    } satisfies CSSProperties,
    td: {
      padding: '6px 4px',
      borderBottom: `1px solid ${isDark ? '#1f2937' : '#f3f4f6'}`,
      verticalAlign: 'middle',
    } satisfies CSSProperties,
    button: {
      border: `1px solid ${isDark ? '#f9fafb' : '#111827'}`,
      borderRadius: '8px',
      padding: '8px 12px',
      background: isDark ? '#f9fafb' : '#111827',
      color: isDark ? '#111827' : '#f9fafb',
      cursor: 'pointer',
      fontSize: '13px',
    } satisfies CSSProperties,
    buttonSecondary: {
      border: `1px solid ${isDark ? '#4b5563' : '#d1d5db'}`,
      borderRadius: '8px',
      padding: '8px 12px',
      background: 'transparent',
      color: isDark ? '#f9fafb' : '#111827',
      cursor: 'pointer',
      fontSize: '13px',
    } satisfies CSSProperties,
    buttonDanger: {
      border: `1px solid ${isDark ? '#fca5a5' : '#dc2626'}`,
      borderRadius: '8px',
      padding: '6px 10px',
      background: 'transparent',
      color: isDark ? '#fca5a5' : '#dc2626',
      cursor: 'pointer',
      fontSize: '12px',
    } satisfies CSSProperties,
    buttonDisabled: {
      opacity: 0.5,
      cursor: 'not-allowed',
    } satisfies CSSProperties,
    error: {
      border: `1px solid ${isDark ? '#7f1d1d' : '#fecaca'}`,
      borderRadius: '8px',
      padding: '10px 12px',
      color: isDark ? '#fecaca' : '#991b1b',
      background: isDark ? '#450a0a' : '#fef2f2',
      fontSize: '13px',
      lineHeight: 1.5,
      whiteSpace: 'pre-wrap',
    } satisfies CSSProperties,
    success: {
      border: `1px solid ${isDark ? '#166534' : '#bbf7d0'}`,
      borderRadius: '8px',
      padding: '10px 12px',
      color: isDark ? '#bbf7d0' : '#166534',
      background: isDark ? '#052e16' : '#f0fdf4',
      fontSize: '13px',
      lineHeight: 1.5,
    } satisfies CSSProperties,
    warning: {
      border: `1px solid ${isDark ? '#854d0e' : '#fde68a'}`,
      borderRadius: '8px',
      padding: '10px 12px',
      color: isDark ? '#fde68a' : '#854d0e',
      background: isDark ? '#422006' : '#fffbeb',
      fontSize: '13px',
      lineHeight: 1.5,
    } satisfies CSSProperties,
    code: {
      fontFamily:
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      fontSize: '11px',
      whiteSpace: 'pre-wrap',
      margin: 0,
    } satisfies CSSProperties,
  };
};
