import { defineIndex } from 'twenty-sdk/define';

import {
  COMMERCIAL_PROPOSAL_XLSX_TEMPLATE_VERSION_FIELD_TEMPLATE_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_XLSX_TEMPLATE_VERSION_INDEX_TEMPLATE_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_XLSX_TEMPLATE_VERSION_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier:
    COMMERCIAL_PROPOSAL_XLSX_TEMPLATE_VERSION_INDEX_TEMPLATE_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier:
    COMMERCIAL_PROPOSAL_XLSX_TEMPLATE_VERSION_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  isUnique: false,
  fields: [
    {
      universalIdentifier: '844e0a21-9a47-4e74-9161-20a19d2212ae',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_XLSX_TEMPLATE_VERSION_FIELD_TEMPLATE_UNIVERSAL_IDENTIFIER,
    },
  ],
});
